//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaintMalachy.Resources.EmailTemplates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaintMalachy.Resources.EmailTemplates.EmailResources", typeof(EmailResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td colspan=&quot;2&quot; style=&quot;background-color:#a2c7a2;padding:15px 5px 5px 15px;&quot;&gt;
        ///                &lt;h3&gt;Baptism Request Details:&lt;/h3&gt;
        ///            &lt;/td&gt;
        ///        &lt;/tr&gt;
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;width:500px;padding:5px;background-color:#ecebeb;border-bottom:1px solid #d0d0d0&quot;&gt;Baptism Date:&amp;nbsp;[[BaptismDate]]&lt;/td&gt;
        ///            &lt;td style=&quot;width:auto;padding:5px;background-color:#e6e6e6;border-bottom:1px solid #d0d0d0&quot;&gt;Dinne [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BaptismOnlineForm {
            get {
                return ResourceManager.GetString("BaptismOnlineForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td colspan=&quot;2&quot; style=&quot;background-color:#a2c7a2;padding:15px 5px 5px 15px;&quot;&gt;
        ///                &lt;h3&gt;Funeral Home Info Sheet:&lt;/h3&gt;
        ///            &lt;/td&gt;
        ///        &lt;/tr&gt;
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;width:500px;padding:5px;background-color:#ecebeb;border-bottom:1px solid #d0d0d0&quot;&gt;Name Of Deceased:&amp;nbsp;[[NameOfDeceased]]&lt;/td&gt;
        ///            &lt;td style=&quot;width:auto;padding:5px;background-color:#e6e6e6;border-bottom:1px solid #d0d0d0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FuneralHomeInfo {
            get {
                return ResourceManager.GetString("FuneralHomeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td colspan=&quot;2&quot; style=&quot;background-color:#a2c7a2;padding:15px 5px 5px 15px;&quot;&gt;
        ///                &lt;h3&gt;Funeral Request Details:&lt;/h3&gt;
        ///            &lt;/td&gt;
        ///        &lt;/tr&gt;
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;width:500px;padding:5px;background-color:#ecebeb;border-bottom:1px solid #d0d0d0&quot;&gt;Name Of Deceased:&amp;nbsp;[[NameOfDeceased]]&lt;/td&gt;
        ///            &lt;td style=&quot;width:auto;padding:5px;background-color:#e6e6e6;border-bottom:1px solid #d0d0d0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FuneralRequestForm {
            get {
                return ResourceManager.GetString("FuneralRequestForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table width=&quot;100%&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td colspan=&quot;2&quot; style=&quot;background-color:#a2c7a2;padding:15px 5px 5px 15px;&quot;&gt;
        ///                &lt;h3&gt;Religious Education Request Details:&lt;/h3&gt;
        ///            &lt;/td&gt;
        ///        &lt;/tr&gt;
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;width:500px;padding:5px;background-color:#ecebeb;border-bottom:1px solid #d0d0d0&quot;&gt;Today&apos;s Date:&amp;nbsp;[[TodayDate]]&lt;/td&gt;
        ///            &lt;td style=&quot;width:auto;padding:5px;background-color:#e6e6e6;border-bottom:1px solid #d0d [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReligiousEdForm {
            get {
                return ResourceManager.GetString("ReligiousEdForm", resourceCulture);
            }
        }
    }
}
